function ClearLevel () {
    level += 1
    CreateLevel()
}
function CreateLevel () {
    if (level == 1) {
        tiles.setCurrentTilemap(tilemap`level2`)
        tiles.placeOnRandomTile(Hero, assets.tile`transparency16`)
        game.setGameOverMessage(false, "GAME OVER!")
        info.startCountdown(15)
    } else if (level == 2) {
        tiles.setCurrentTilemap(tilemap`level2`)
        info.startCountdown(20)
        tiles.placeOnRandomTile(Hero, assets.tile`transparency16`)
        game.setGameOverMessage(false, "GAME OVER!")
    } else if (level == 3) {
        tiles.setCurrentTilemap(tilemap`level3`)
        info.startCountdown(25)
        game.setGameOverMessage(false, "GAME OVER!")
        tiles.placeOnRandomTile(Hero, assets.tile`transparency16`)
    } else if (level == 4) {
        tiles.setCurrentTilemap(tilemap`level4`)
        info.startCountdown(30)
        tiles.placeOnRandomTile(Hero, assets.tile`transparency16`)
        game.setGameOverMessage(false, "GAME OVER!")
    }
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`transparency16`, function (sprite, location) {
    info.changeScoreBy(1)
    ClearLevel()
})
let Hero: Sprite = null
let level = 0
level = 1
info.setScore(0)
Hero = sprites.create(img`
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    ...............................
    `, SpriteKind.Player)
controller.moveSprite(Hero)
tiles.setCurrentTilemap(tilemap`level1`)
tiles.placeOnRandomTile(Hero, assets.tile`transparency16`)
scene.cameraFollowSprite(Hero)
CreateLevel()
music.play(music.stringPlayable("G F G A C5 F E C ", 120), music.PlaybackMode.LoopingInBackground)
